use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use tagpath::{family, parser};

const FIXTURE: &str = include_str!("../fixtures/tsift-token-savings.json");

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u32,
    token_estimate: String,
    cases: Vec<BenchmarkCase>,
}

#[derive(Debug, Deserialize)]
struct BenchmarkCase {
    name: String,
    surface: String,
    minimum_savings_percent: f64,
    raw_symbols: Vec<RawSymbol>,
    tagpath_families: Vec<ExpectedFamily>,
    #[serde(default)]
    context_pack_inputs: Option<ContextPackInputs>,
}

#[derive(Debug, Deserialize)]
struct RawSymbol {
    identifier: String,
    file: String,
    line: usize,
    context: String,
}

#[derive(Debug, Deserialize)]
struct ExpectedFamily {
    canonical: String,
    count: usize,
    aliases: BTreeMap<String, String>,
}

#[derive(Debug, Deserialize, Serialize)]
struct ContextPackInputs {
    #[serde(default)]
    next_context: Vec<serde_json::Value>,
    #[serde(default)]
    diff: Vec<serde_json::Value>,
    #[serde(default)]
    test: Vec<serde_json::Value>,
    #[serde(default)]
    log: Vec<serde_json::Value>,
}

#[test]
fn tsift_token_savings_fixture_groups_symbols_by_tagpath_family() {
    let fixture: Fixture = serde_json::from_str(FIXTURE).unwrap();
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.token_estimate, "ceil(utf8_bytes / 4)");

    for case in &fixture.cases {
        assert!(
            matches!(
                case.surface.as_str(),
                "search" | "explain" | "session-review" | "context-pack"
            ),
            "unexpected fixture surface in {}: {}",
            case.name,
            case.surface
        );

        let mut observed_counts = BTreeMap::<String, usize>::new();
        for raw_symbol in &case.raw_symbols {
            let convention = parser::detect_convention(&raw_symbol.identifier);
            let parsed = parser::parse(&raw_symbol.identifier, convention);
            *observed_counts.entry(parsed.tags.join("_")).or_default() += 1;
        }

        let expected_counts: BTreeMap<String, usize> = case
            .tagpath_families
            .iter()
            .map(|expected| (expected.canonical.clone(), expected.count))
            .collect();
        assert_eq!(
            observed_counts, expected_counts,
            "fixture counts must match parsed raw symbols for {}",
            case.name
        );

        for expected in &case.tagpath_families {
            let generated = family::generate_family(&expected.canonical);
            assert_eq!(
                generated.aliases, expected.aliases,
                "fixture aliases must stay generated by tagpath for {}",
                expected.canonical
            );
        }
    }
}

#[test]
fn tsift_token_savings_fixture_compacts_all_preview_surfaces() {
    let fixture: Fixture = serde_json::from_str(FIXTURE).unwrap();
    assert_eq!(
        fixture.cases.len(),
        4,
        "fixture should cover search, explain, session-review, and context-pack previews"
    );
    assert_eq!(
        fixture
            .cases
            .iter()
            .map(|case| case.surface.as_str())
            .collect::<Vec<_>>(),
        vec!["search", "explain", "session-review", "context-pack"]
    );

    for case in &fixture.cases {
        let raw_preview = render_raw_preview(case);
        let tagpath_preview = render_tagpath_preview(case);
        let raw_tokens = estimate_tokens(&raw_preview);
        let tagpath_tokens = estimate_tokens(&tagpath_preview);
        let saved_percent = ((raw_tokens - tagpath_tokens) as f64 / raw_tokens as f64) * 100.0;

        assert!(
            tagpath_tokens < raw_tokens,
            "{} should be smaller as a tagpath family/alias preview\nraw:\n{}\ncompact:\n{}",
            case.name,
            raw_preview,
            tagpath_preview
        );
        assert!(
            saved_percent >= case.minimum_savings_percent,
            "{} saved {saved_percent:.1}% ({raw_tokens} -> {tagpath_tokens}), expected at least {:.1}%",
            case.name,
            case.minimum_savings_percent
        );
    }
}

#[test]
fn tsift_token_savings_context_pack_case_carries_handle_refs() {
    let fixture: Fixture = serde_json::from_str(FIXTURE).unwrap();
    let case = fixture
        .cases
        .iter()
        .find(|case| case.surface == "context-pack")
        .expect("fixture should include context-pack");
    let inputs = case
        .context_pack_inputs
        .as_ref()
        .expect("context-pack case should include raw context-pack inputs");

    assert!(!inputs.next_context.is_empty());
    assert!(!inputs.diff.is_empty());
    assert!(!inputs.test.is_empty());
    assert!(!inputs.log.is_empty());

    let raw = serde_json::to_string(inputs).unwrap();
    assert!(raw.contains("ontology_refs"));
    assert!(raw.contains(".naming/tags/"));
    assert!(raw.contains("summary_refs"));
    assert!(raw.contains("artifact"));
}

fn render_raw_preview(case: &BenchmarkCase) -> String {
    let mut preview = render_raw_symbol_preview(&case.raw_symbols);
    if let Some(inputs) = &case.context_pack_inputs {
        preview.push('\n');
        preview.push_str(&serde_json::to_string(inputs).unwrap());
    }
    preview
}

fn render_tagpath_preview(case: &BenchmarkCase) -> String {
    let mut preview = render_tagpath_family_alias_preview(&case.tagpath_families);
    if let Some(inputs) = &case.context_pack_inputs {
        let section_rows = [
            ("next_context", inputs.next_context.len()),
            ("diff", inputs.diff.len()),
            ("test", inputs.test.len()),
            ("log", inputs.log.len()),
        ]
        .into_iter()
        .filter(|(_, count)| *count > 0)
        .map(|(section, count)| format!("{section}\tcount:{count}\texpand:tsift {section}"))
        .collect::<Vec<_>>()
        .join("\n");
        preview.push('\n');
        preview.push_str(&section_rows);
    }
    preview
}

fn render_raw_symbol_preview(raw_symbols: &[RawSymbol]) -> String {
    raw_symbols
        .iter()
        .map(|symbol| {
            let convention = parser::detect_convention(&symbol.identifier);
            let parsed = parser::parse(&symbol.identifier, convention);
            let role = parsed.role.as_deref().unwrap_or("none");
            let shape = parsed.shape.as_deref().unwrap_or("none");
            format!(
                "{}:{}\t{}\t{}\tconvention:{}\ttags:[{}]\trole:{}\tshape:{}",
                symbol.file,
                symbol.line,
                symbol.context,
                symbol.identifier,
                parsed.convention,
                parsed.tags.join(","),
                role,
                shape
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_tagpath_family_alias_preview(families: &[ExpectedFamily]) -> String {
    families
        .iter()
        .map(|family| {
            let aliases = family
                .aliases
                .iter()
                .map(|(convention, spelling)| format!("{convention}:{spelling}"))
                .collect::<Vec<_>>()
                .join(",");
            format!(
                "{}\tcount:{}\taliases:[{}]",
                family.canonical, family.count, aliases
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn estimate_tokens(output: &str) -> usize {
    output.len().div_ceil(4)
}
