version = 1
name = "c"

convention = "snake_case"
immutable = true
singular = true

[vectors]
join = "_"
namespace = "__"

[contexts.variable]
convention = "snake_case"

[contexts.function]
convention = "snake_case"

[contexts.typedef]
convention = "snake_case"
suffix = "_t"

[contexts.struct]
convention = "snake_case"
suffix = "_t"

[contexts.enum]
convention = "snake_case"
suffix = "_t"

[contexts.enum_member]
convention = "UPPER_SNAKE_CASE"

[contexts.constant]
convention = "UPPER_SNAKE_CASE"

[contexts.macro]
convention = "UPPER_SNAKE_CASE"

[contexts.parameter]
convention = "snake_case"

[contexts.file]
convention = "snake_case"

[patterns]
factory = "{module}_{name}_create"
init = "{module}_{name}_init"
destroy = "{module}_{name}_destroy"
getter = "{module}_{name}_get"
setter = "{module}_{name}_set"
type = "{name}_t"

[externals]
preserve_casing = true
join_with = "_"

[tags]
open = true
