version = 1
name = "shell"

convention = "snake_case"
immutable = true
singular = true

[vectors]
join = "_"
namespace = "__"

[contexts.variable]
convention = "snake_case"

[contexts.function]
convention = "snake_case"

[contexts.private_function]
convention = "snake_case"
prefix = "_"

[contexts.environment]
convention = "UPPER_SNAKE_CASE"

[contexts.constant]
convention = "UPPER_SNAKE_CASE"

[contexts.alias]
convention = "snake_case"

[contexts.file]
convention = "kebab-case"

[patterns]
private = "_{name}"
setter = "set_{name}"
getter = "get_{name}"
predicate = "is_{name}"
type = "{Name}"

[externals]
preserve_casing = true
join_with = "_"

[tags]
open = true
